set -g status-bg '#131313'
set -g status-fg '#ffffff'
set-option -g status-position top

setw -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g mouse on

bind r source-file ~/.config/tmux/tmux.conf

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# -----------------------------------------------------------------------------
# Window Navigation (Alt + number)
# -----------------------------------------------------------------------------
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-u select-window -t 1
bind -n M-i select-window -t 2
bind -n M-o select-window -t 3
bind -n M-p select-window -t 4
bind -n M-n select-window -t 5
bind -n M-m select-window -t 6

# -----------------------------------------------------------------------------
# Pane Navigation (Alt + hjkl)
# -----------------------------------------------------------------------------
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
